# AWS Configuration
# Contains all AWS-related settings including region, S3 bucket configuration, and DynamoDB table settings
aws:
  region: eu-north-1  # AWS region for all services
  s3:
    bucket_name: content-curator  # Name of the S3 bucket for storing content
  dynamodb:
    table_name: content-curator-metadata  # DynamoDB table for storing content metadata

# Logging Configuration
# Controls how the application logs are generated and stored
logging:
  file:  # Name of the log file
  rotation: 10 MB  # Maximum size of each log file before rotation
  retention: 5  # Number of rotated log files to keep
  level: DEBUG  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message} | {extra}"  # Log message format

# Pipeline Configuration
# Global settings for the content curation pipeline
# pipeline:

# RSS Configuration
# Settings specific to RSS feed processing
rss:
  rss_url_file: data/rss_urls.txt  # Path to file containing RSS feed URLs
  default_max_items: 5  # Maximum number of items to fetch from each RSS feed

# Summarizer Configuration
# Settings for the content summarization process
summarizer:
  model_name: gemini-1.5-flash  # Name of the AI model to use for summarization
  default_summary_types: ["brief", "standard"]  # Types of summaries to generate by default 

# Curator Configuration
# Settings for the content curation process
curator:
  default_most_recent: 15  # Default number of most recent items to include in newsletters
  content_summary_types: ["brief", "standard"]  # Types of summaries to include in newsletters

# Distributor Configuration
distributor:
  email:
    smtp_server: smtp.gmail.com  # SMTP server for sending emails
    smtp_port: 587  # SMTP port (587 for TLS, 465 for SSL)
    sender_email:  # Email address to send from (leave empty to use env var)
    sender_password: ""  # App password for Gmail (leave empty to use env var)
    default_recipient: thomas.lees112@gmail.com  # Default recipient email address
    subject_prefix: "[Content Curator] "  # Prefix for email subject lines