name: Daily Content Curation

on:
  push:
  schedule:
    - cron: '0 9 * * *'  # Every day at 9am UTC
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  content-curation:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: eu-north-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    - name: Run fetch & process stage
      run: |
        uv run python scripts/main.py --fetch --process

    - name: Run summarize stage
      run: uv run python scripts/main.py --summarize

    - name: Run curate stage
      run: uv run python scripts/main.py --curate

    - name: Run distribute stage
      run: uv run python scripts/main.py --distribute

